# Generated by Django 5.2.8 on 2025-11-18 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_load_trouble_brewing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('socket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_vote_toggle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alignment', models.CharField(choices=[('townsfolk', 'Townsfolk'), ('outsider', 'Outsider'), ('minion', 'Minion'), ('demon', 'Demon'), ('traveller', 'Traveller')], max_length=20)),
                ('first_night', models.BooleanField(default=False)),
                ('other_night', models.BooleanField(default=False)),
                ('is_once_per_game', models.BooleanField(default=False)),
                ('requires_target', models.BooleanField(default=False)),
                ('night_priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting for players'), ('ASSIGNING_ROLES', 'Assigning roles'), ('FIRST_NIGHT', 'First night'), ('NIGHT', 'Night'), ('DAY_DISCUSSION', 'Day discussion'), ('NOMINATION', 'Nomination phase'), ('VOTING', 'Voting phase'), ('NIGHT_RESULTS', 'Night result reveal'), ('GAME_END', 'Game end')], default='WAITING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_day', models.IntegerField(default=1)),
                ('current_night', models.IntegerField(default=1)),
                ('active_night_queue', models.JSONField(default=list)),
                ('player_order', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_poisoned', models.BooleanField(default=False)),
                ('drunk_real_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drunk_players', to='game.role')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignment', to='game.player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.role')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominator_confirmed', models.BooleanField(default=False)),
                ('nominee_confirmed', models.BooleanField(default=False)),
                ('votes_for', models.IntegerField(default=0)),
                ('executed', models.BooleanField(default=False)),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_made', to='game.player')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_received', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('night_order', models.JSONField(default=list)),
                ('roles', models.ManyToManyField(related_name='scripts', to='game.role')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.script'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voted', models.BooleanField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.nomination')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
