# Generated by Django 5.2.8 on 2025-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_roleassignment_died_at_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='night_order',
            field=models.JSONField(default=dict),
        ),
    ]
