# Generated by Django 5.2.8 on 2025-11-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_script_night_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
