# Generated by Django 5.2.8 on 2025-11-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for players'), ('ASSIGNING_ROLES', 'Assigning roles'), ('ROLE', 'Showing roles'), ('FIRST_NIGHT', 'First night'), ('NIGHT', 'Night'), ('DAY_DISCUSSION', 'Day discussion'), ('NOMINATION', 'Nomination phase'), ('VOTING', 'Voting phase'), ('NIGHT_RESULTS', 'Night result reveal'), ('GAME_END', 'Game end')], default='WAITING', max_length=30),
        ),
    ]
