# Generated by Django 5.2.8 on 2025-11-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del rol', null=True, upload_to='roles/'),
        ),
    ]
