# Generated by Django 5.2.8 on 2025-11-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_role_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='image',
        ),
        migrations.AddField(
            model_name='role',
            name='image_path',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
